// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ManuallyTaskStarting(executeStatus bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if executeStatus {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><p>В настоящее время задача уже выполняется</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n            function sendToken(){\n                let tokenElement = document.getElementById(\"token_validation\")\n\n                console.log(tokenElement.value)\n\n                let xhr = new XMLHttpRequest();\n                let json = JSON.stringify({\n                    token: tokenElement.value,\n                });\n\n                console.log(json)\n\n                xhr.open(\"POST\", '/api?task_management')\n                xhr.setRequestHeader('Content-type', 'application/json; charset=utf-8');\n                xhr.send(json);\n                xhr.onload = function() {\n                    if (xhr.status != 200) { // анализируем HTTP-статус ответа, если статус не 200, то произошла ошибка\n                        alert(`Ошибка ${xhr.status}: ${xhr.statusText}`); // Например, 404: Not Found\n                    } else { // если всё прошло гладко, выводим результат\n                        alert(`Готово, получили ${xhr.response.length} байт`); // response -- это ответ сервера\n                    }\n                };\n            }\n        </script> <div><input name=\"token\" id=\"token_validation\" value=\"\"> <button onclick=\"sendToken()\">отправить</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
