// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BaseComponentScripts() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_BaseComponentScripts_9697`,
		Function: `function __templ_BaseComponentScripts_9697(){const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = ` + "`" + `${wsProtocol}//${window.location.host}/ws` + "`" + `;
    let arrLogs = [];
    let socket = new WebSocket(wsUrl);

    function wsConnect(){
        socket.onopen = function() {
            console.log('WebSocket соединение установлено');
            //updateStatus(true);
            //addMessage('Подключено к серверу', 'server');
        };

        socket.onmessage = function(event) {
            //console.log('Получено сообщение:', event.data);

            processingMessage(event.data);
            //addMessage(` + "`" + `Сервер: ${event.data}` + "`" + `, 'server');
        };

        socket.onclose = function(event) {
            console.log('WebSocket соединение закрыто');
            //updateStatus(false);
            //addMessage('Соединение закрыто', 'server');
        };

        socket.onerror = function(error) {
            console.error('WebSocket ошибка:', error);
            //addMessage('Произошла ошибка соединения', 'server');
        };
    }
    
    function wsDisconnect() {
        if (socket) {
            socket.close();
            socket = null;
        }
    }

    function processingMessage(data){
        let jsonObj = JSON.parse(data)

        if (jsonObj.type == "logs") {
            console.log("приняты логи:", jsonObj.data)

            arrLogs.unshift(jsonObj.data)

            if (arrLogs.length == 31){
                arrLogs.pop();
            }

            displayLogs(arrLogs);
        }

        if (jsonObj.type == "manually_task") {            
            if (jsonObj.settings.error != "") {
                //если есть ошибка
                printErrorMessage(true);

                disabledInputAndButtonSendToken(false);                

                return
            } 
            
            //показ области для для вывода информации о выполнении процесса
            let idInformationArea = document.getElementById("informationArea");
            if (idInformationArea != null) {
                idInformationArea.hidden = false;
            }

            printErrorMessage(false);

            //делать доступными для взаимодействия кнопку и поле ввода
            //только после выполнения задачи
        }
    }

    // форматирования времени
    function formatTimestamp(timestamp) {
        const date = new Date(timestamp);
        
        return date.toLocaleString('ru-RU');
    }

    // CSS класс по уровню логирования
    function getLogLevelClass(level) {
        const levelMap = {
            'INFO': 'log-info',
            'WARNING': 'log-warning',
            'ERROR': 'log-error',
            'DEBUG': 'log-info'
        };

        return levelMap[level] || 'log-info';
    }

    // CSS класс для уровня
    function getLevelColorClass(level) {
        return ` + "`" + `log-level-${level.toLowerCase()}` + "`" + `;
    }

    // статистика по логам
    function getLogStats(logs) {
        return {
            total: logs.length,
            info: logs.filter(log => log.level === 'INFO').length,
            warning: logs.filter(log => log.level === 'WARNING').length,
            error: logs.filter(log => log.level === 'ERROR').length,
            debug: logs.filter(log => log.level === 'DEBUG').length
        };
    }

    // Отображение логов
    function displayLogs(logs) {
        const logsContainer = document.getElementById('areaLogs');
        if (logsContainer == null){
            return
        }
    
        // Очищаем контейнер
        logsContainer.innerHTML = '';
    
        // Создаем список логов
        const logsList = document.createElement('div');
    
        logs.forEach(log => {
            const logItem = document.createElement('div');
            logItem.className = ` + "`" + `log-item ${getLogLevelClass(log.level)}` + "`" + `;
        
            // Создаем HTML для элемента лога
            logItem.innerHTML = ` + "`" + `
                <div>
                    <span class="log-timestamp">${formatTimestamp(log.timestamp)}</span>
                    <span class="log-level ${getLevelColorClass(log.level)}">${log.level}</span>
                    <span class="log-message">${log.message}</span>
                </div>
                ${log.details ? ` + "`" + `<div class="log-details"><small>${log.details}</small></div>` + "`" + ` : ''}
                ${log.user ? ` + "`" + `<div class="log-user"><small>Пользователь: ${log.user}</small></div>` + "`" + ` : ''}
            ` + "`" + `;
        
            logsList.appendChild(logItem);
        });
    
        // Добавляем статистику
        const stats = getLogStats(logs);
        const statsElement = document.createElement('div');
        statsElement.innerHTML = ` + "`" + `
            <hr>
            <div style="color: #666; font-size: 0.9em;">
                Всего событий: ${stats.total} | 
                INFO: ${stats.info} | 
                WARNING: ${stats.warning} | 
                ERROR: ${stats.error} | 
                DEBUG: ${stats.debug}
            </div>
        ` + "`" + `;
    
        logsContainer.appendChild(statsElement);
        logsContainer.appendChild(logsList);
    }
    
    function sendToken(){
        let tokenElement = document.getElementById("inputToken");
        let jsonData = JSON.stringify({
            "type": "manually_task",
            "settings": {
                "token": tokenElement.value
            }
        });

        socket.send(jsonData)

        //временно выключаем поле ввода токена и кнопку его отправки
        disabledInputAndButtonSendToken(true);
    }

    function setHandlerForButtonSendToken(){
        let buttonSend = document.getElementById("buttonSendToken");
        if (buttonSend == null) {
            return;
        }

        buttonSend.onclick = sendToken;
    }

    function printErrorMessage(isLook){
        let idMsgTErr = document.getElementById("messageTokenError");
        if (idMsgTErr != null) {
            idMsgTErr.hidden = !isLook;
        }
    }

    function disabledInputAndButtonSendToken(isDisabled){
        let idInputToken = document.getElementById("inputToken")
        if (idInputToken != null) {
            idInputToken.value = "";
            idInputToken.disabled = isDisabled;
        }

        let idButtonSendToken = document.getElementById("buttonSendToken")
        if (idButtonSendToken != null) {
            idButtonSendToken.disabled = isDisabled;
        }
    }

    //обработчик соединений по websocket
    wsConnect();

    //обработчик на кнопку отправляющую токен на сервер
    setHandlerForButtonSendToken();
}`,
		Call:       templ.SafeScript(`__templ_BaseComponentScripts_9697`),
		CallInline: templ.SafeScriptInline(`__templ_BaseComponentScripts_9697`),
	}
}

var _ = templruntime.GeneratedTemplate
