// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BaseComponentScripts() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_BaseComponentScripts_0a49`,
		Function: `function __templ_BaseComponentScripts_0a49(){// только для проверки работы функции
    //
    //function getAlert(){
    //    alert("some message");
    //}

    //getAlert();

    function wsConnect(){
        const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
        const wsUrl = ` + "`" + `${wsProtocol}//${window.location.host}/ws` + "`" + `;
            
        socket = new WebSocket(wsUrl);

        socket.onopen = function() {
            console.log('WebSocket соединение установлено');
            //updateStatus(true);
            //addMessage('Подключено к серверу', 'server');
        };

        socket.onmessage = function(event) {
            console.log('Получено сообщение:', event.data);
            //addMessage(` + "`" + `Сервер: ${event.data}` + "`" + `, 'server');
        };

        socket.onclose = function(event) {
            console.log('WebSocket соединение закрыто');
            //updateStatus(false);
            //addMessage('Соединение закрыто', 'server');
        };

        socket.onerror = function(error) {
            console.error('WebSocket ошибка:', error);
            //addMessage('Произошла ошибка соединения', 'server');
        };
    }

    wsConnect();
}`,
		Call:       templ.SafeScript(`__templ_BaseComponentScripts_0a49`),
		CallInline: templ.SafeScriptInline(`__templ_BaseComponentScripts_0a49`),
	}
}

var _ = templruntime.GeneratedTemplate
